I. Numpy

1) a.

In [3]:
import numpy as np

In [4]:
a_array  = np.zeros(10)

In [5]:
a_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

b.

In [7]:
b_array = np.arange(10 ,40)

In [8]:
b_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

c.

In [10]:
c_matrix = np.ones((2,2), dtype=int)

In [11]:
c_matrix

array([[1, 1],
       [1, 1]])

d.

In [13]:
d_matrix = np.ones((3,2), dtype=float)

In [14]:
d_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

e.

In [16]:
X = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [17]:
e_matrix = np.full_like(X, 7)

In [18]:
e_matrix

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

f.

In [20]:
f_matrix= np.eye(3, dtype=int)

In [21]:
f_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
g_array = np.random.randint(1, 11, size=3)

In [23]:
g_array

array([ 1,  9, 10])

h.

In [25]:
h_matrix = np.random.rand(3,3,3)

In [26]:
h_matrix

array([[[0.26666431, 0.27583123, 0.59135554],
        [0.17548362, 0.01079675, 0.23595801],
        [0.14179407, 0.81460541, 0.10431851]],

       [[0.74981378, 0.44025457, 0.96629138],
        [0.10424515, 0.5316888 , 0.74555499],
        [0.7212426 , 0.9603394 , 0.47993082]],

       [[0.47102128, 0.3022849 , 0.26299885],
        [0.87038339, 0.12033838, 0.16289097],
        [0.42121046, 0.22266523, 0.78482469]]])

2)

In [28]:
X = np.array([
      [1,2,3,4,],
      [5,6,7,8],
      [9,10,11,12,],
      [13,14,15,16]

])

a.

In [30]:
X[0],X[-1]

(array([1, 2, 3, 4]), array([13, 14, 15, 16]))

b.

In [32]:
X[0,0]

1

c.

In [34]:
X[-1,-1]

16

d.

In [36]:
X[:2,:2]

array([[1, 2],
       [5, 6]])

e.

In [38]:
X[-1] = 1

In [39]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

f.

In [41]:
(X.T)

array([[ 1,  5,  9,  1],
       [ 2,  6, 10,  1],
       [ 3,  7, 11,  1],
       [ 4,  8, 12,  1]])

g.

In [43]:
(np.linalg.inv(X))


LinAlgError: Singular matrix

II.   Pandas Series

1.

In [ ]:
import pandas as pd

In [ ]:
X = ['Mahlet','Mastewat','Wondesen','Tewodros','Mekdes','Haymanot']

a.

In [ ]:
name_series = pd.Series(X, name = "Name of group members")

In [ ]:
name_series

b.

In [ ]:
(name_series.values)

c.

In [ ]:
name_series.index = ("first member","second member","third member","fourth member","fifth member","sixth member")

In [ ]:
name_series

d.

In [ ]:
(name_series.head(1))

In [ ]:
(name_series.tail(1))

e.

In [ ]:
(name_series[::-1])

3.

In [ ]:
import pandas as pd

In [ ]:
Y = pd.Series([-1,2,3,-4,2,6,-9,10])

a.

In [ ]:
("Negative elements :")

In [ ]:
(Y[Y<0])

b.

In [ ]:
("\nNumbers higher than 2 :")

In [ ]:
(Y[Y>2])

c.

In [ ]:
mean = Y.mean()

In [ ]:
(f"\nNumbers higher than the mean({mean : .2f}):")

In [ ]:
Y[Y > mean]

d.

In [ ]:
("\nNumbers equal to 2 or 10 :")

In [ ]:
(Y[(Y == 2) | (Y == 10)])

4.

In [ ]:
import pandas as pd

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

a.

In [ ]:
("None of the elements is zero:", not (0 in X.values))

b.

In [ ]:
("Any of the elements is zero:", 0 in X.values)

In [ ]:
(f"the sum is {X.sum()}, the mean is {X.mean():.2f}, and the maximum is {X.max()}")

III.     Pandas DataFrame

1)

In [ ]:
group_df= pd.DataFrame({
    'First Name' : ['Mahlet', 'Mastewat', 'Wondesen', 'Tewodros', 'Mekdes', 'Haymanot'],
    'Sex' : ['Female', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Grade 12 Maths' : [78, 84, 90, 76, 83 ,80],
    'Year of Birth' : [1997, 1996, 1994, 1996, 1995, 1996]
})

a.

In [ ]:
group_df.columns = ['Name', 'Sex', 'Grade 12 Maths ', 'Year of birth'] 

In [ ]:
group_df

In [ ]:
group_df.index.name= 'Index'

In [ ]:
group_df

b.

In [ ]:
group_df = group_df.drop('Sex', axis=1)

In [ ]:
group_df

c.

In [ ]:
new_student = pd.DataFrame({'Name': ['Samrawit'], 'Grade 12 Maths': [82], 'Year of Birth': [1995]})

In [ ]:
group_df = pd.concat([group_df, new_student], ignore_index=True)

In [ ]:
group_df

d.

In [ ]:
group_df = group_df.iloc[:-1]

In [ ]:
group_df

e.

In [ ]:
("first 3 elements: \n", group_df.head(3))

f.

In [ ]:
("last two elements: \n", group_df.tail(2))

g.

In [ ]:
group_df.insert(1,'Sex',['Female', 'Female', 'Male', 'Male', 'Female', 'Female'])

In [ ]:
group_df

In [ ]:
("\nSex of the first three elements:\n", group_df['Sex'].head(3))

h.

In [ ]:
group_df['color preference'] = ['red', 'blue','green', 'yellow', 'white','purple']

In [ ]:
group_df

i.

In [ ]:
male_students =group_df[group_df['Sex'] == 'Male']

In [ ]:
male_students

j.

In [ ]:
("\nBasic statistics:\n", group_df.describe())

k.

In [ ]:
group_df = group_df.reset_index(drop=True)

In [ ]:
group_df

2.

a.

In [ ]:
group_df = pd.DataFrame({
    'Sex': [
        'Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female'
    ],
    'Mother Occupation': [
        'Wage Employed', 'Unemployed', 'Unemployed', 'Unemployed', 'Unemployed', 'Unemployed', 'Merchant', 'Chief', 'Merchant', 'Teacher', 'Unemployed', 'Merchant', 'Merchant', 'Unemployed', 'Unemployed', 'Unemployed', 'Unemployed', 'Unemployed', 'Farmer', 'Unemployed', 'Household', 'Merchant', 'Merchant', 'Household', 'Merchant', 'Teacher', 'Merchant', 'Merchant', 'Teacher', 'Farmer', 'Farmer', 'Wage Employed', 'Merchant', 'Farmer', 'Farmer', 'Wage Employed', 'Merchant', 'Unemployed'
    ],
    'Father Occupation': [
        'Wage Employed', 'Wage Employed', 'Wage Employed', 'Wage Employed', 'Wage Employed', 'Merchant', 'Wage Employed', 'Driver', 'Merchant', 'Merchant', 'Teacher', 'Wage Employed', 'Wage Employed', 'Unemployed', 'Wage Employed', 'Wage Employed', 'Merchant', 'Daily Labourer', 'Farmer', 'Farmer', 'Wage Employed', 'Farmer', 'Farmer', 'Torno', 'Teacher', 'Teacher', 'Wage Employed', 'Wage Employed', 'Driver', 'Farmer', 'Farmer', 'Wage Employed', 'Wage Employed', 'Farmer', 'Farmer', 'Wage Employed', 'Contractor', 'Wage Employed'
    ],
    'Household Residence': [
        'Urban', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban', 'Rural', 'Urban', 'Urban', 'Rural', 'Urban', 'Rural', 'Rural', 'Rural', 'Urban', 'Urban', 'Urban', 'Urban', 'Rural', 'Urban', 'Urban', 'Rural', 'Rural', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban', 'Rural', 'Rural', 'Urban', 'Urban', 'Rural', 'Rural', 'Urban', 'Urban'],
    'Primary School Type': [
        'Government School', 'Private School', 'Government School', 'Government School', 'Government School', 'Private School', 'Private School', 'Private School', 'Government School', 'Government School', 'Government School', 'Private School', 'Private School', 'Private School', 'Government School', 'Government School', 'Private School', 'Government School', 'Government School', 'Government School', 'Private School', 'Government School', 'Government School', 'Private School', 'Government School', 'Government School', 'Government School', 'Government School', 'Private School', 'Government School', 'Government School', 'Government School', 'Private School', 'Government School', 'Government School', 'Government School', 'Private School', 'Government School'
    ],
    'Grade 12 SAT Score': [
        69, 70, 60, 60, 65, 70, 64, 60, 70, 68, 55, 52, 52, 70, 70, 70, 65, 52, 63, 53, 72, 46, 46, 60, 56, 56, 55, 55, 65, 40, 40, 53, 82, 40, 40, 53, 65, 56
    ],
    'Average Monthly Pocket Money': [
        1500, 1000, 2000, 2000, 3000, 3000, 2000, 1500, 3000, 950, 6000, 2000, 2000, 2000, 3000, 3000, 1000, 900, 500, 600, 2000, 1000, 1000, 100, 1000, 500, 1000, 1000, 3000, 500, 500, 500, 2000, 500, 500, 700, 2000, 3000
    ],
    'Average Weekly Study Hours During Exam Month': [
        28, 20, 20, 20, 28, 30, 15, 19, 23, 28, 46, 15, 25, 20, 28, 28, 20, 10, 16, 21, 21, 42, 42, 14, 14, 14, 20, 28, 50, 10, 10, 12, 15, 24, 24, 24, 16, 16
    ],
    'Freshman CGPA': [
        3.77, 3.29, 3.2, 3.2, 3.3, 3, 3.33, 3.26, 3.5, 3.75, 3.22, 3.33, 3.33, 3, 3.3, 3.3, 3.67, 3.36, 3.3, 3.41, 3.5, 3.6, 3.6, 3.28, 2.9, 2.9, 3.39, 3.39, 3.33, 3.16, 3.16, 3.36, 3.3, 3.16, 3.16, 3.36, 3.56, 3.1
    ],
    'Having a Crush in Freshman': [
        'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'
    ]
})




b.

In [ ]:
group_df

c.

In [ ]:
group_df.describe()

In [ ]:
pip install matplotlib

In [ ]:
pip install seaborn

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
# Histogram of Grade 12 SAT Scores
plt.figure(figsize=(8, 6))
group_df['Grade 12 SAT Score'].hist()
plt.title('Histogram of Grade 12 SAT Scores')
plt.xlabel('SAT Score')
plt.ylabel('Frequency')
plt.show()

# Scatter plot of Freshman CGPA vs Average Weekly Study Hours During Exam Month
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Average Weekly Study Hours During Exam Month', y='Freshman CGPA', data=group_df)
plt.title('Freshman CGPA vs Average Weekly Study Hours During Exam Month')
plt.xlabel('Average Weekly Study Hours During Exam Month')
plt.ylabel('Freshman CGPA')
plt.show()


d.

In [ ]:
 # Histogram of Grade 12 SAT Scores
plt.figure(figsize=(8, 6))
group_df['Grade 12 SAT Score'].hist()
plt.title('Histogram of Grade 12 SAT Scores')
plt.xlabel('SAT Score')
plt.ylabel('Frequency')
plt.show()

# Histogram of Average Monthly Pocket Money
plt.figure(figsize=(8, 6))
group_df['Average Monthly Pocket Money'].hist()
plt.title('Histogram of Average Monthly Pocket Money')
plt.xlabel('Pocket Money')
plt.ylabel('Frequency')
plt.show()

# Histogram of Average Weekly Study Hours During Exam Month
plt.figure(figsize=(8, 6))
group_df['Average Weekly Study Hours During Exam Month'].hist()
plt.title('Histogram of Average Weekly Study Hours During Exam Month')
plt.xlabel('Study Hours')
plt.ylabel('Frequency')
plt.show()

e.

In [ ]:
# Box plot of Grade 12 SAT Scores
plt.figure(figsize=(8, 6))
group_df.boxplot(column='Grade 12 SAT Score')
plt.title('Box Plot of Grade 12 SAT Scores')
plt.xlabel('SAT Score')
plt.show()

# Box plot of Average Monthly Pocket Money
plt.figure(figsize=(8, 6))
group_df.boxplot(column='Average Monthly Pocket Money')
plt.title('Box Plot of Average Monthly Pocket Money')
plt.xlabel('Pocket Money')
plt.show()

# Box plot of Average Weekly Study Hours During Exam Month
plt.figure(figsize=(8, 6))
group_df.boxplot(column='Average Weekly Study Hours During Exam Month')
plt.title('Box Plot of Average Weekly Study Hours During Exam Month')
plt.xlabel('Study Hours')
plt.show()

f.

In [ ]:
!pip install scipy

In [ ]:
from scipy.stats import ttest_ind

In [ ]:


male_sat = group_df.loc[group_df['Sex'] == 'Male', 'Grade 12 SAT Score']
female_sat = group_df.loc[group_df['Sex'] == 'Female', 'Grade 12 SAT Score']

t_stat, p_value =stats.ttest_ind (male_sat, female_sat)

print(f"t-statistic: {t_stat:.2f}")
print(f"p-value: {p_value:.4f}")

# If the p-value is less than the chosen significance level (e.g., 0.05),
# we can conclude that there is a statistically significant difference
# in the mean SAT scores between male and female students.
# We have recieved so many warning that scipy is not found, which we had an environment issue ,we try our best and  couldn't solve it .


g.

In [ ]:
from scipy.stats import ttest_ind
crush_yes = group_df.loc[group_df['Having a Crush During Freshman Year']== 'Yes', 'Freshman CGPA']
crush_no = group_df.loc[group_df['Having a Crush During Freshman Year']=='No', 'Freshman CGPA']

t_stat, p_value =stats.ttest_ind (crush_yes, crush_no)

print(f"t-statistic: {t_stat:.2f}")
print(f"p-value: {p_value:.4f}")



# If the p-value is less than the chosen significance level (e.g., 0.05),
# We can conclude that having a crush during the freshman year
# Significantly affecting 



H.

In [ ]:
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Average Weekly Study Hours During Exam Month' ,
y='Freshman CGPA' , data =group_df)
plt.title('Freshman CGPA vs Average Weekly Study Hours')
plt.xlabel('Average Weekly Study Hours')
plt.ylabel('Freshman CGPA')
plt.show()

Class Work

In [ ]:
"""1. Test weather there is statistically singnificant mean reading score difference between male and female sudents.
2. Test weather there is statistically singnificant mean writing score difference between male and female sudents.
3. Test weather there is statistically singnificant overall mean score (math+reading+writing) difference between male and female sudents."""


In [ ]:
import pandas as pd
from scipy import stats

In [ ]:
#Create the data
data = {
    'gender': ['female', 'female', 'female', 'male', 'male'],
    'race/ethnicity': ['group B', 'group C', 'group B', 'group A', 'group C'],
    'parental level of education': ["bachelor's degree", 'some college', "master's degree", "associate's degree", 'some college'],
    'lunch': ['standard', 'standard', 'standard', 'free/reduced', 'standard'],
    'test preparation course': ['none', 'completed', 'none', 'none', 'none'],
    'math score': [72, 69, 90, 47, 76],
    'reading score': [72, 90, 95, 57, 78],
    'writing score': [74, 88, 93, 44, 75]
}

In [ ]:
#Create a DataFrame
df = pd.DataFrame(data)

In [ ]:
#Separate the data into two groups: male and female
female_reading_scores = df[df['gender'] == 'female']['reading score']
male_reading_scores = df[df['gender'] == 'male']['reading score']

t_stat, p_value = stats.ttest_ind(female_reading_scores, male_reading_scores)


In [ ]:
#Print the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")


In [ ]:
#Interpretation
if p_value < 0.05:
    print("There is a statistically significant difference in the mean reading scores between male and female students.")
else:
    print("There is no statistically significant difference in the mean reading scores between male and female students.")


In [ ]:
#Separate the data into two groups: male and female
female_writing_scores = df[df['gender'] == 'female']['writing score']
male_writing_scores = df[df['gender'] == 'male']['writing score']


In [ ]:
# Perform an independent samples t-test
t_stat, p_value = stats.ttest_ind(female_writing_scores, male_writing_scores)

# Print the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")


In [ ]:
if p_value < 0.05:
    print("There is a statistically significant difference in the mean writing scores between male and female students.")
else:
    print("There is no statistically significant difference in the mean writing scores between male and female students.")


In [ ]:
# Calculate the overall mean score (math + reading + writing)
df['overall score'] = df['math score'] + df['reading score'] + df['writing score']

#Separate the data into two groups: male and female
female_overall_scores = df[df['gender'] == 'female']['overall score']
male_overall_scores = df[df['gender'] == 'male']['overall score']

# Perform an independent samples t-test
t_stat, p_value = stats.ttest_ind(female_overall_scores, male_overall_scores)

print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")


In [ ]:
if p_value < 0.05:
    print("There is a statistically significant difference in the overall mean scores between male and female students.")
else:
    print("There is no statistically significant difference in the overall mean scores between male and female students.")


      STUDENT NAME         ID NO
    1 MAHILET  TEKLE      1601955 
    2 WENDESEN TESHOME    1501521
    3 TEWODROS KASAHUN    1601650
    4 HAYMANOT ASRAT      1601248
    5 MEKDES   WENDESEN   1601854 
    6 MASTAWET MEHIRETE   1601337